ALTER TABLE audit_histories ADD COLUMN IF NOT EXISTS resolved_entity_label VARCHAR(512);
ALTER TABLE audit_histories ADD COLUMN IF NOT EXISTS token_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE audit_histories ADD COLUMN IF NOT EXISTS rank_position INTEGER NOT NULL DEFAULT 0;
ALTER TABLE audit_histories ADD COLUMN IF NOT EXISTS sentiment_intensity DOUBLE PRECISION NOT NULL DEFAULT 0;
