ALTER TABLE jobs ADD COLUMN IF NOT EXISTS brand_color VARCHAR(64) NOT NULL DEFAULT '#4F46E5';
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS logo_url VARCHAR(2048);
ALTER TABLE projects ADD COLUMN IF NOT EXISTS brand_color VARCHAR(64) NOT NULL DEFAULT '#4F46E5';
ALTER TABLE projects ADD COLUMN IF NOT EXISTS logo_url VARCHAR(2048);
